function parameters_single_simulation = generate_parameters_single_simulation(all_parameters, i, equation_type)
    if strcmp(equation_type, 'crude_estimates') || strcmp(equation_type, 'suppressed_crude_estimates')
        parameters_single_simulation = struct('beta', all_parameters.beta_estimates(i), ...
                                              'sigma', all_parameters.sigma_estimates(i), ...
                                              'gamma', all_parameters.gamma_estimates(i), ...
                                              'okinawa_population', all_parameters.okinawa_population, ...
                                              'initial_infected', all_parameters.initial_infected_estimates(i));
    elseif strcmp(equation_type, 'multiple_channels')
        parameters_single_simulation = struct('sigma', all_parameters.sigma_estimates(i), ...
                                              'gamma', all_parameters.gamma_estimates(i), ...
                                              'okinawa_population', all_parameters.okinawa_population, ...
                                              'initial_infected', all_parameters.initial_infected_estimates(i), ...
                                              'beta_presymptomatic', all_parameters.beta_presymptomatic(i), ...
                                              'beta_symptomatic', all_parameters.beta_symptomatic(i), ...
                                              'beta_asymptomatic', all_parameters.beta_asymptomatic(i));
    else
        error('equations unknown.')
    end
end